import Uppy from "@uppy/core";
import Tus from "@uppy/tus";
import request, { getApiOrigin } from "@/util/request";

// The normal /chat/file/upload route is intentionally reserved for tiny
// attachments. Production Nginx may apply a conservative body limit to the
// regular API route, whereas /echo-files/ is configured for resumable Tus
// chunks. Route anything above 512 KiB through Tus to avoid a size-dependent
// 413 gap between the two upload paths.
export const SMALL_FILE_LIMIT = 512 * 1024;

const getSecureTusEndpoint = (endpoint) => {
  if (!endpoint) throw new Error("服务端未返回文件上传地址");
  const apiOrigin = getApiOrigin();
  const target = new URL(endpoint, window.location.href);
  const api = apiOrigin ? new URL(apiOrigin) : null;
  if (api?.protocol === "https:") {
    // Older servers may still return an absolute HTTP URL. Never let that reach
    // Uppy: upgrade only the same public host, otherwise fail with a clear error.
    if (target.protocol === "http:" && target.hostname === api.hostname) {
      target.protocol = "https:";
    }
    if (target.protocol !== "https:") {
      throw new Error("生产环境文件上传必须使用 HTTPS，请检查 TUSD_PUBLIC_ENDPOINT");
    }
    if (target.hostname !== api.hostname) {
      throw new Error("上传地址不是当前生产域名，请检查 TUSD_PUBLIC_ENDPOINT");
    }
  }
  return target.toString();
};

const isSecureResumableUrl = (value) => {
  try {
    const target = new URL(value, window.location.href);
    const apiOrigin = getApiOrigin();
    const api = apiOrigin ? new URL(apiOrigin) : null;
    // Only production has the HTTPS invariant. Do not invalidate normal
    // localhost/LAN resumable uploads while developing.
    if (api?.protocol !== "https:") return true;
    return target.protocol === "https:" && target.hostname === api.hostname;
  } catch (_) {
    return false;
  }
};

// tus-js-client stores resumable upload URLs in localStorage. Filter out URLs
// generated by older proxy deployments (for example http://host/files/<id>) so
// a fixed deployment does not keep retrying an insecure historical location.
const createSecureUrlStorage = () => ({
  findUploadsByFingerprint(fingerprint) {
    const prefix = `tus::${fingerprint}::`;
    const uploads = [];
    try {
      for (let index = 0; index < window.localStorage.length; index += 1) {
        const key = window.localStorage.key(index);
        if (!key || !key.startsWith(prefix)) continue;
        const raw = window.localStorage.getItem(key);
        const upload = raw ? JSON.parse(raw) : null;
        if (upload?.uploadUrl && isSecureResumableUrl(upload.uploadUrl)) {
          uploads.push({ ...upload, urlStorageKey: key });
        } else {
          window.localStorage.removeItem(key);
        }
      }
    } catch (_) {
      // Storage is optional. A browser privacy mode can disable it entirely.
    }
    return Promise.resolve(uploads);
  },
  findAllUploads() {
    return Promise.resolve([]);
  },
  removeUpload(key) {
    try { window.localStorage.removeItem(key); } catch (_) { /* optional storage */ }
    return Promise.resolve();
  },
  addUpload(fingerprint, upload) {
    const key = `tus::${fingerprint}::${Math.round(Math.random() * 1e12)}`;
    try { window.localStorage.setItem(key, JSON.stringify(upload)); } catch (_) { /* optional storage */ }
    return Promise.resolve(key);
  },
});

/**
 * 使用一个独立 Uppy 实例上传单个聊天文件。
 * Tus 会保存上传 URL 指纹，因此刷新或网络中断后再次选择同一文件可继续传输。
 * receiverId（好友）与 groupId（群）二选一。
 */
export const uploadChatFileWithTus = async ({ file, receiverId, groupId, onProgress, onIntent }) => {
  const intentResponse = await request.post("/files/chat/upload-intents", {
    ...(receiverId != null ? { receiverId } : {}),
    ...(groupId != null ? { groupId } : {}),
    fileName: file.name,
    contentType: file.type || "application/octet-stream",
    size: file.size,
  });
  if (intentResponse.code !== 200) {
    throw new Error(intentResponse.message || "创建大文件上传任务失败");
  }

  const intent = intentResponse.data;
  // 上传一开始就通知调用方（拿到 fileId 落本地任务，刷新后可恢复）
  if (typeof onIntent === "function") {
    try {
      onIntent(intent);
    } catch (e) {
      console.warn("onIntent 回调失败", e);
    }
  }
  const uppy = new Uppy({
    autoProceed: false,
    // 实际最大值由后端上传意图返回，避免前端、tusd 与后端出现三处不一致。
    restrictions: { maxNumberOfFiles: 1, maxFileSize: intent.maxFileSize || Number.MAX_SAFE_INTEGER },
    meta: {
      fileId: intent.fileId,
      uploadToken: intent.uploadToken,
    },
  });
  uppy.use(Tus, {
    endpoint: getSecureTusEndpoint(intent.tusEndpoint),
    chunkSize: 5 * 1024 * 1024,
    removeFingerprintOnSuccess: true,
    storeFingerprintForResuming: true,
    urlStorage: createSecureUrlStorage(),
    allowedMetaFields: ["fileId", "uploadToken", "name", "type"],
  });

  const uppyFileId = uppy.addFile({
    name: file.name,
    type: file.type || "application/octet-stream",
    data: file,
  });
  uppy.on("upload-progress", (uploadedFile, progress) => {
    if (uploadedFile.id !== uppyFileId || typeof onProgress !== "function") return;
    const total = progress.bytesTotal || file.size;
    onProgress(total ? Math.min(100, Math.round((progress.bytesUploaded / total) * 100)) : 0);
  });

  try {
    const result = await uppy.upload();
    if (result.failed?.length) {
      const failure = result.failed[0]?.error;
      throw failure instanceof Error ? failure : new Error("大文件上传失败");
    }
    if (!result.successful?.length) throw new Error("大文件上传未完成");

    // 完成确认会在后端读取完整文件并计算 SHA-256；大文件不能沿用全局 60 秒请求超时。
    const completed = await request.post(`/files/${intent.fileId}/complete`, null, {
      timeout: 30 * 60 * 1000,
    });
    if (completed.code !== 200) throw new Error(completed.message || "文件完成校验失败");
    return completed.data;
  } finally {
    // Uppy 5 使用 destroy() 释放插件与事件；清理失败不能覆盖已经完成的上传结果。
    try {
      uppy.destroy();
    } catch (error) {
      console.warn("释放 Tus 上传实例失败", error);
    }
  }
};
