CREATE TABLE `file_asset` (
  `id` char(36) NOT NULL COMMENT '后端生成的文件与 tus 上传 ID',
  `owner_id` bigint NOT NULL COMMENT '上传用户',
  `receiver_id` bigint DEFAULT NULL COMMENT '聊天接收者',
  `purpose` varchar(32) NOT NULL COMMENT '用途：CHAT 等',
  `original_name` varchar(255) NOT NULL,
  `content_type` varchar(255) NOT NULL,
  `expected_size` bigint NOT NULL,
  `actual_size` bigint DEFAULT NULL,
  `sha256` char(64) DEFAULT NULL,
  `storage_key` varchar(255) DEFAULT NULL COMMENT '非公开永久存储键',
  `upload_token` char(64) NOT NULL COMMENT 'Tus 创建校验令牌',
  `access_token` char(64) NOT NULL COMMENT '受控下载令牌',
  `status` varchar(20) NOT NULL COMMENT 'UPLOADING/UPLOADED/READY/CANCELLED/EXPIRED',
  `scan_status` varchar(20) NOT NULL COMMENT 'PENDING/CLEAN/REJECTED',
  `expires_at` datetime NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_asset_upload_token` (`upload_token`),
  UNIQUE KEY `uk_file_asset_access_token` (`access_token`),
  KEY `idx_file_asset_owner_status` (`owner_id`, `status`),
  KEY `idx_file_asset_expiry_status` (`expires_at`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
